# -------------------------------------------------------------------------------------------
# * SECCIÓN 1: EJEMPLO BÁSICO DE VARIABLES EN PYTHON
# ? ESTA SECCIÓN ENSEÑA CÓMO DEFINIR Y UTILIZAR VARIABLES BÁSICAS EN UN CONTEXTO DE ADMINISTRACIÓN DE SISTEMAS.
# ? UNA VARIABLE ES UN CONTENEDOR QUE ALMACENA UN VALOR QUE PUEDE SER UTILIZADO O MODIFICADO MÁS TARDE.
# -------------------------------------------------------------------------------------------

# * DEFINIR LAS VARIABLES: nombre_servidor (cadena de texto), cpu_uso (decimal), memoria_disponible (entero), es_activo (booleano)
# * ESTAS VARIABLES REFLEJAN EL ESTADO DE UN SERVIDOR.

# * EJEMPLO DE UNA VARIABLE:
# ? UNA VARIABLE ES UN ESPACIO DONDE SE ALMACENA INFORMACIÓN. AQUÍ, 'nombre_servidor' ES UNA VARIABLE QUE ALMACENA EL NOMBRE DEL SERVIDOR.
# ? LAS VARIABLES PUEDEN ALMACENAR DIFERENTES TIPOS DE DATOS COMO TEXTO, NÚMEROS O VALORES DE VERDADERO/FALSO.

# * IMPRIMIR ES UNA FUNCIÓN QUE MUESTRA EN LA PANTALLA EL VALOR DE LAS VARIABLES.
# ? USAMOS print() PARA MOSTRAR INFORMACIÓN O RESULTADOS DEL CÓDIGO.

# * AHORA VAMOS A CAMBIAR LOS VALORES DE LAS VARIABLES.
# ? POR EJEMPLO, SI OPTIMIZAMOS EL SERVIDOR, EL USO DE CPU Y LA MEMORIA DISPONIBLE PUEDEN CAMBIAR.

# * IMPRIMIMOS LOS NUEVOS VALORES DESPUÉS DEL CAMBIO.
# ? CUANDO CAMBIAMOS EL VALOR DE UNA VARIABLE, EL VALOR ANTERIOR SE REEMPLAZA.

# TODO: ESCRIBE AQUÍ TU CÓDIGO PARA DEFINIR LAS VARIABLES Y MOSTRAR LOS VALORES INICIALES.


# -------------------------------------------------------------------------------------------
# * SECCIÓN 2: VERIFICACIÓN DE TIPOS DE VARIABLES
# ? EN ESTA SECCIÓN SE VERIFICAN LOS TIPOS DE DATOS DE LAS VARIABLES USANDO LA FUNCIÓN type().
# ? LAS VARIABLES PUEDEN ALMACENAR DIFERENTES TIPOS DE DATOS, COMO NÚMEROS, TEXTO O BOOLEANOS, Y CON type() PODEMOS SABER QUÉ TIPO DE DATOS ESTÁN ALMACENANDO.
# -------------------------------------------------------------------------------------------

# * DEFINIR LAS VARIABLES: nombre_servidor, cpu_uso, memoria_disponible, es_activo

# * VERIFICAR Y MOSTRAR EL TIPO DE CADA VARIABLE.
# ? type() ES UNA FUNCIÓN QUE NOS DICE QUÉ TIPO DE DATOS CONTIENE UNA VARIABLE.

# TODO: ESCRIBE AQUÍ TU CÓDIGO PARA VERIFICAR EL TIPO DE LAS VARIABLES.


# -------------------------------------------------------------------------------------------
# * SECCIÓN 3: CAMBIO DINÁMICO DE TIPO DE VARIABLES
# ? ESTA SECCIÓN MUESTRA CÓMO CAMBIAR DINÁMICAMENTE EL TIPO DE UNA VARIABLE EN PYTHON.
# -------------------------------------------------------------------------------------------

# * DEFINIR LA VARIABLE cpu_uso COMO UN NÚMERO DECIMAL.

# * CAMBIAR EL TIPO DE LA VARIABLE cpu_uso PARA QUE SEA UNA CADENA DE TEXTO.

# * IMPRIMIR LA VARIABLE ANTES Y DESPUÉS DEL CAMBIO DE TIPO.

# TODO: ESCRIBE AQUÍ TU CÓDIGO PARA CAMBIAR EL TIPO DE UNA VARIABLE Y MOSTRAR EL RESULTADO.


# -------------------------------------------------------------------------------------------
# * SECCIÓN 4: VARIABLES Y ENTRADA DEL USUARIO
# ? EN ESTA SECCIÓN SE CAPTURA LA ENTRADA DEL USUARIO UTILIZANDO LA FUNCIÓN input().
# -------------------------------------------------------------------------------------------

# * SOLICITAR AL USUARIO QUE INTRODUZCA UN NUEVO NOMBRE PARA EL SERVIDOR.

# * ALMACENAR EL NOMBRE DEL SERVIDOR EN UNA VARIABLE.

# * IMPRIMIR EL NUEVO NOMBRE DEL SERVIDOR.

# TODO: ESCRIBE AQUÍ TU CÓDIGO PARA SOLICITAR UNA ENTRADA AL USUARIO Y MOSTRARLA.


# -------------------------------------------------------------------------------------------
# * SECCIÓN 5: CONVERSIÓN DE TIPOS A PARTIR DE LA ENTRADA DEL USUARIO
# ? EN ESTA SECCIÓN SE CONVIERTE LA ENTRADA DEL USUARIO A OTROS TIPOS DE DATOS, COMO ENTEROS.
# -------------------------------------------------------------------------------------------

# * SOLICITAR AL USUARIO QUE INTRODUZCA UN NÚMERO DE PROCESOS PARA EJECUTAR EN PARALELO.

# * CONVERTIR LA ENTRADA A UN NÚMERO ENTERO Y ALMACENARLA EN UNA VARIABLE.

# * IMPRIMIR LA CANTIDAD DE PROCESOS QUE SE EJECUTARÁN EN PARALELO.

# TODO: ESCRIBE AQUÍ TU CÓDIGO PARA CONVERTIR UNA ENTRADA DE TEXTO A UN ENTERO Y MOSTRAR EL RESULTADO.


# -------------------------------------------------------------------------------------------
# * SECCIÓN 6: USO DE LISTAS Y DICCIONARIOS
# ? DEMOSTRAMOS EL USO DE LISTAS Y DICCIONARIOS EN UN CONTEXTO PRÁCTICO DE ADMINISTRACIÓN DE SISTEMAS.
# -------------------------------------------------------------------------------------------

# * EJEMPLO DE LISTA: USUARIOS CONECTADOS
# ? UNA LISTA ES UNA COLECCIÓN DE ELEMENTOS QUE SE PUEDEN MODIFICAR. AQUÍ USAMOS UNA LISTA PARA ALMACENAR USUARIOS CONECTADOS.

# * AGREGAR UN NUEVO USUARIO A LA LISTA.

# * IMPRIMIR LA LISTA ACTUALIZADA DE USUARIOS CONECTADOS.

# * EJEMPLO DE DICCIONARIO: INFORMACIÓN DEL SERVIDOR
# ? UN DICCIONARIO ALMACENA PARES DE CLAVE-VALOR. AQUÍ USAMOS UN DICCIONARIO PARA ALMACENAR LA INFORMACIÓN DE UN SERVIDOR.

# * IMPRIMIR EL DICCIONARIO CON LA INFORMACIÓN DEL SERVIDOR.

# TODO: ESCRIBE AQUÍ TU CÓDIGO PARA TRABAJAR CON LISTAS Y DICCIONARIOS, AGREGANDO Y MOSTRANDO INFORMACIÓN.

# -------------------------------------------------------------------------------------------
# * AUTOEVALUACIÓN FINAL :
# 1. CREA UNA VARIABLE QUE ALMACENE EL NOMBRE DE UN SERVIDOR (CADENA DE TEXTO).
# 2. DEFINE UNA LISTA QUE ALMACENE LOS NOMBRES DE DOS SERVICIOS ACTIVOS EN ESE SERVIDOR.
# 3. DEFINE UN DICCIONARIO QUE CONTENGA LOS SIGUIENTES DATOS: NOMBRE DEL SERVIDOR, CANTIDAD DE SERVICIOS, Y SI EL SERVIDOR ESTÁ ACTIVO O NO (BOOLEANO).
# 4. IMPRIME TODOS LOS DATOS ALMACENADOS, INCLUYENDO LA LISTA DE SERVICIOS.
# 5. CAMBIA EL ESTADO DEL SERVIDOR A 'NO ACTIVO' Y ACTUALIZA EL DICCIONARIO.
# -------------------------------------------------------------------------------------------

# TODO: ESCRIBE AQUÍ TU CÓDIGO DE AUTOEVALUACIÓN PARA PRACTICAR LO APRENDIDO.