# -------------------------------------------------------------------------------------------
# * SECCIÓN 1: EJEMPLO BÁSICO DE CONDICIONES EN PYTHON
# ? ESTA SECCIÓN ENSEÑA CÓMO UTILIZAR CONDICIONES SIMPLES EN UN CONTEXTO DE ADMINISTRACIÓN DE SISTEMAS.
# ? UNA CONDICIÓN SE UTILIZA PARA TOMAR DECISIONES BASADAS EN UNA EXPRESIÓN VERDADERA O FALSA.
# -------------------------------------------------------------------------------------------

# * PEDIR AL USUARIO QUE INTRODUZCA EL USO DE CPU.
# * SI EL USO DE CPU ES MAYOR AL 85%, SE MUESTRA UNA ALERTA, SI NO, SE INDICA QUE TODO ESTÁ NORMAL.

# TODO: ESCRIBE AQUÍ TU CÓDIGO PARA PEDIR EL USO DE CPU Y EVALUAR SI ES MAYOR AL 85%.


# -------------------------------------------------------------------------------------------
# * SECCIÓN 2: CONDICIONES MÚLTIPLES CON ELIF
# ? EN ESTA SECCIÓN SE UTILIZA ELIF PARA EVALUAR DIFERENTES CONDICIONES.
# ? PODEMOS VERIFICAR SI TANTO EL USO DE CPU COMO EL USO DE MEMORIA ESTÁN POR ENCIMA DE UN UMBRAL.
# -------------------------------------------------------------------------------------------

# * PEDIR AL USUARIO QUE INTRODUZCA EL USO DE MEMORIA.
# * VERIFICAR SI TANTO EL USO DE CPU COMO EL USO DE MEMORIA SON MAYORES AL 85%.
# * USAR ELIF PARA EVALUAR SI UNO DE LOS DOS RECURSOS (CPU O MEMORIA) ESTÁ ALTO.
# * SI AMBOS ESTÁN BAJOS, MOSTRAR UN MENSAJE DE QUE TODO ESTÁ EN ORDEN.

# TODO: ESCRIBE AQUÍ TU CÓDIGO PARA EVALUAR EL USO DE CPU Y MEMORIA CON CONDICIONES MÚLTIPLES.


# -------------------------------------------------------------------------------------------
# * SECCIÓN 3: CONDICIONES ANIDADAS
# ? ESTA SECCIÓN DEMUESTRA CÓMO SE PUEDEN ANIDAR CONDICIONES PARA TOMAR DECISIONES MÁS COMPLEJAS.
# ? SE EVALÚA SI UN SERVIDOR ESTÁ CONECTADO A LA RED Y SI EL USO DE CPU ES ALTO.
# -------------------------------------------------------------------------------------------

# * SOLICITAR AL USUARIO SI EL SERVIDOR ESTÁ CONECTADO A LA RED (SÍ/NO).
# * SI EL SERVIDOR ESTÁ CONECTADO, EVALUAR EL USO DE CPU Y MOSTRAR UNA ALERTA SI ES ALTO.
# * SI NO ESTÁ CONECTADO, INDICAR QUE EL SERVIDOR ESTÁ DESCONECTADO.

# TODO: ESCRIBE AQUÍ TU CÓDIGO PARA EVALUAR EL ESTADO DE LA RED Y EL USO DE CPU USANDO CONDICIONES ANIDADAS.


# -------------------------------------------------------------------------------------------
# * SECCIÓN 4: USO DE OPERADORES DE COMPARACIÓN Y LÓGICOS
# ? LOS OPERADORES LÓGICOS COMO "AND" Y "OR" NOS PERMITEN COMBINAR MÚLTIPLES CONDICIONES.
# ? EN ESTE EJEMPLO, VERIFICAMOS SI EL USO DE CPU Y MEMORIA ESTÁN POR DEBAJO DEL 50%.
# -------------------------------------------------------------------------------------------

# * EVALUAR SI EL USO DE CPU Y EL USO DE MEMORIA ESTÁN POR DEBAJO DEL 50% USANDO "AND".
# * SI SOLO UNO DE LOS RECURSOS ESTÁ POR DEBAJO DEL 50%, USAR "OR" PARA MOSTRARLO.
# * SI NINGUNO ESTÁ POR DEBAJO DEL 50%, INDICAR QUE AMBOS RECURSOS ESTÁN ALTOS.

# TODO: ESCRIBE AQUÍ TU CÓDIGO PARA EVALUAR EL USO DE CPU Y MEMORIA USANDO OPERADORES LÓGICOS.


# -------------------------------------------------------------------------------------------
# * SECCIÓN 5: EVALUACIÓN COMBINADA
# ? AQUÍ COMBINAMOS EL ESTADO DEL SERVIDOR CON SU SEGURIDAD. SI EL SERVIDOR ESTÁ ACTUALIZADO
# ? Y TIENE RECURSOS BAJOS, ES SEGURO Y EFICIENTE. SI NO TIENE ACTUALIZACIONES, SE MOSTRARÁ UNA ALERTA.
# -------------------------------------------------------------------------------------------

# * PEDIR AL USUARIO SI EL SERVIDOR TIENE ACTUALIZACIONES INSTALADAS (SÍ/NO).
# * VERIFICAR SI EL USO DE CPU Y MEMORIA ESTÁN BAJOS Y SI EL SERVIDOR ESTÁ ACTUALIZADO.
# * SI TIENE RECURSOS ALTOS Y NO TIENE ACTUALIZACIONES, MOSTRAR UNA ALERTA DE ALTO RIESGO.
# * SI ESTÁ ACTUALIZADO Y TIENE RECURSOS BAJOS, MOSTRAR QUE EL SERVIDOR ES SEGURO Y EFICIENTE.

# TODO: ESCRIBE AQUÍ TU CÓDIGO PARA EVALUAR EL ESTADO DEL SERVIDOR Y MOSTRAR EL ESTADO DE SEGURIDAD.


# -------------------------------------------------------------------------------------------
# * AUTOEVALUACIÓN FINAL:
# 1. SOLICITA EL NOMBRE DEL SERVIDOR Y GUARDALO EN UNA VARIABLE.
# 2. SOLICITA EL USO DE CPU Y EL USO DE MEMORIA DEL SERVIDOR.
# 3. SI EL USO DE CPU O MEMORIA ES MAYOR AL 85%, MUESTRA UNA ALERTA.
# 4. SOLICITA SI EL SERVIDOR TIENE ACTUALIZACIONES INSTALADAS Y GUARDA EL RESULTADO.
# 5. MUESTRA UN RESUMEN FINAL QUE INCLUYA EL NOMBRE DEL SERVIDOR, USO DE CPU, USO DE MEMORIA Y SI ESTÁ ACTUALIZADO.
# 6. SI EL SERVIDOR TIENE RECURSOS ALTOS Y NO TIENE ACTUALIZACIONES, MUESTRA UNA ALERTA DE ALTO RIESGO.
# -------------------------------------------------------------------------------------------

# TODO: ESCRIBE AQUÍ TU CÓDIGO PARA LA AUTOEVALUACIÓN FINAL.
